apiVersion: v1
kind: Pod
metadata:
  name: test-runner
spec:
  containers:
    - name: go-test
      image: mi_imagen:latest
      imagePullPolicy: Never
      command: ["go", "test", "./server"]
  restartPolicy: Never